default_language_version:
    python: python3.7
repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.4
    hooks:
      - id: seed-isort-config
        args: [--exclude=tests/.*\.py]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-docstrings', 'darglint']
